import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Header from "@/components/section/Header";
import SessionProviderContext from "@/components/contexts/SessionContexts";
import Footer from "@/components/section/Footer";
import ProductContextProvider from "@/components/contexts/ProductContext";
import CartContextProvider from "@/components/contexts/CartContext";
import RecordeOrderContextProvider from "@/components/contexts/RecordOrderContext";
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <SessionProviderContext>
        <ProductContextProvider>
          <CartContextProvider>
            <RecordeOrderContextProvider>
              <body className={inter.className}>
                <Header className="flex justify-between items-center px-12 py-4" />
                {children}
                <Footer className="bg-secondary flex flex-col m-4" />
              </body>
            </RecordeOrderContextProvider>
          </CartContextProvider>
        </ProductContextProvider>
      </SessionProviderContext>
    </html>
  );
}
